sudo: required
language: java
jdk: openjdk11

services:
  - docker

script:
  - ./mvnw clean install
  - ./mvnw test


after_success:
  - ./mvnw compile jib:build -Djib.to.image=registry.hub.docker.com/vayusense/ic:lastest -Djib.to.auth.username=$USERHUB -Djib.to.auth.password=$PASSHUB